version : '3'

services:
    grafana: 
        image: grafana/grafana:6.7.4-ubuntu
        container_name: grafana_m
        ports:  
            - "3000:3000"
        volumes: 
            - "$PWD/grafana:/var/lib/grafana/"
        depends_on:
            - influxdb
            - telegraf

    telegraf: 
        container_name: push_metric
        image: telegraf 
        depends_on:
            - influxdb
        volumes: 
            -  "$PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro"

    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb_t
        volumes: 
            - "$PWD/data:/var/lib/influxdb"
        